////////////////////////////////////////---- AUTH ROUTES-----\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "name": "Test3",
    "surname": "Test Test",
    "email": "test3@test.com",
    "roles": ["USER_ROLE"],
    "password": "password1"
}

###
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "password1"
}

////////////////////////////////////////---- POSTS ROUTES-----\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
###
GET http://localhost:3000/api/posts?page=1

###
GET http://localhost:3000/api/posts/606134cf3140e9156cbb087a

###
POST http://localhost:3000/api/posts 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDYzNGUwYzg5ZWY3ZTFlNTgyZDk5MWUiLCJpYXQiOjE2MTcxMjA3ODAsImV4cCI6MTYxNzIwNzE4MH0.UWWz126f-NF1bUaY3yVsedi1SlHyE545Ip7d9ExrHFI

{
    "title": "Titulo de prueba 1",
    "subtitle": "Subtitulo de prueba",
    "img_path": "https://picsum.photos/800/300",
    "article": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, veniam molestias magni saepe eligendi natus? Odit, consequatur sed minima error aliquid alias illo unde cupiditate distinctio autem aliquam architecto reprehenderit!"
}

###
PUT http://localhost:3000/api/posts/606134cf3140e9156cbb087a
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDYyNjdmY2EyY2UzYTBiNzQ5NDhiZDIiLCJpYXQiOjE2MTcwNzAyOTMsImV4cCI6MTYxNzE1NjY5M30.TEhf04HYvRN9Zkm31ne408z7ua1FFBOYNUNbRd-p0pE

{
    "title": "Titulo de prueba 1",
    "subtitle": "Subtitulo de prueba",
    "img_path": "https://picsum.photos/800/300",
    "article": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quia, veniam molestias magni saepe eligendi natus? Odit, consequatur sed minima error aliquid alias illo unde cupiditate distinctio autem aliquam architecto reprehenderit!"
}

###
DELETE http://localhost:3000/api/posts/60627a105a2cab2fbc4cd1bb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDYyNjdmY2EyY2UzYTBiNzQ5NDhiZDIiLCJpYXQiOjE2MTcwNjkwOTAsImV4cCI6MTYxNzA2OTE3Nn0.8nvuNvlU3pHoPfP_5il5U6HRNDEXQer1BcbaXL_1EQE
