///////////////////////---- AUTH ROUTES-----\\\\\\\\\\\\\\\\\\\\\\\\
###
// Registrarse, rol usuario maximo admitido.
POST http://localhost:8000/api/auth/signup
Content-Type: application/json

{
    "name": "Test4",
    "surname": "Test Test",
    "email": "test4@test.com",
    "roles": ["USER_ROLE"],
    "password": "password1"
}

###
// Loguearse.
POST http://localhost:8000/api/auth/signin
Content-Type: application/json

{
    "email": "ferrada20@gmail.com",
    "password": "nalanoel25"
}

###
// Refresh del token.
GET  http://localhost:8000/api/auth/refresh
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDYzNGRlNzg5ZWY3ZTFlNTgyZDk5MWMiLCJpYXQiOjE2MTk1Mzc4MjIsImV4cCI6MTYxOTYyNDIyMn0.Aw7glcJ29OG6Sd6GoapaHVaF2udLn8pOxHeniuOsQRQ