///////////////////////---- AUTH ROUTES-----\\\\\\\\\\\\\\\\\\\\\\\\
###
// Registrarse, rol usuario maximo admitido.
POST http://localhost:8000/api/auth/signup
Content-Type: application/json

{
    "name": "Dario",
    "surname": "Mariño Ferrada",
    "email": "ferrada24@gmail.com",
    "roles": ["USER_ROLE"],
    "password": "password86"
}

###
// Loguearse.
POST http://localhost:8000/api/auth/signin
Content-Type: application/json

{
    "email": "ferrada22@gmail.com",
    "password": "password86"
}

###
// Refresh del token.
GET  http://localhost:8000/api/auth/refresh
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkyZjM0Yzg3OTNhMTJlNjA1MjVmYmYiLCJpYXQiOjE2MjAyNDM4MzcsImV4cCI6MTYyMDMzMDIzN30.lz3ufxvaPplLwKWbeH3-EN4dm9Zd3Ruq_BZRPwX1vP8