//////////////////////////////---- POSTS ROUTES-----\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

###
//Buscar posts por pagina.
GET https://api-backend-myblog.herokuapp.com/api/posts?page=1

###
// Buscar posts por author id y/o pagina.
GET http://localhost:8000/api/posts?search=titulo&page=1


###
// Buscar posts por author id y/o pagina.
GET http://localhost:8000/api/posts?author=608ee8190f3f03319ccc4f3a&page=1

###
// Buscar por id del post.
GET http://localhost:3000/api/posts/606903c5ce874c2caceefbc4

###
// Crear post, minimo rango usuario registrado.
//necesita img en formato "multipart/form-data"
POST http://localhost:8000/api/posts 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDYyNjdmY2EyY2UzYTBiNzQ5NDhiZDIiLCJpYXQiOjE2MTc0ODkxMTcsImV4cCI6MTYxNzU3NTUxN30.ht7mf3hfhGVWJjxz94Mul21D9jRe2iE131qWQpamB4A

{
    "title": "Titulo de prueba 23:00",
    "subtitle": "Subtitulo de prueba",
    "article": "articleID.md"
}

###
// Modificar post, restringido para author o rango administrador/moderador.
PUT http://localhost:3000/api/posts/606903c5ce874c2caceefbc7
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDYyNjdmY2EyY2UzYTBiNzQ5NDhiZDIiLCJpYXQiOjE2MTc0ODkxMTcsImV4cCI6MTYxNzU3NTUxN30.ht7mf3hfhGVWJjxz94Mul21D9jRe2iE131qWQpamB4A

{
    "title": "Titulo de prueba 2",
    "subtitle": "Subtitulo de prueba editado2",
    "article": "articleID.md"
}

###
// Eliminar post, restringido para author o rango administrador/moderador.
DELETE http://localhost:3000/api/posts/60677056917ef436b8a004d8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDY3NDZhYmI1MTI1ODA0ZTA1NTBlNWUiLCJpYXQiOjE2MTczODEwMzUsImV4cCI6MTYxNzQ2NzQzNX0.MPIFdgKHOQKFQCK2-gS-VSYkJP2RGeHLxMCfh_Wdnkg
