///////////////////////---- USERS ROUTES-----\\\\\\\\\\\\\\\\\\\\\\\\
###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/606284948cf2111b882f68bc

###
PUT http://localhost:3000/api/users/60650930e181ff2d203619d0
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDYyNjdmY2EyY2UzYTBiNzQ5NDhiZDIiLCJpYXQiOjE2MTcyMzE3OTksImV4cCI6MTYxNzMxODE5OX0.sSc2zGgecN56WJgbU8zenyqlnMfZb14CAKGxHKf8KhU

{
    "name": "Test9",
    "surname": "Test Test",
    "email": "test9@test.com",
    "roles": ["MODERATOR_ROLE"],
    "newPassword": "password1",
    "oldPassword": "password1"
}