///////////////////////---- USERS ROUTES-----\\\\\\\\\\\\\\\\\\\\\\\\
###
// Buscar usuarios por pagina (ruta abierta información de usuario limitada)
GET https://api-backend-myblog.herokuapp.com/api/users?page=1

###
// Buscar usuario por ID (ruta abierta información de usuario limitada)
GET http://localhost:3000/api/users/60679ca961415b353c7cff06

###
// Actualizar usuario, restringido a dueño de la cuenta o rango Administrador(modificar rol, solo administrador).
PUT http://localhost:8000/api/users/6068d2e0815245211c5f2428
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDYyNjdmY2EyY2UzYTBiNzQ5NDhiZDIiLCJpYXQiOjE2MTk5MzE4NDYsImV4cCI6MTYyMDAxODI0Nn0.9VteLXEaCws49sbqGcUSwkhLHWTt9cABEV_X1j9tctE

{
    "name": "Test5",
    "surname": "Test Test",
    "email": "test5@test.com",
    
    "newPassword": "",
    "oldPassword": "",
    "facebookUrl": "https://es-es.facebook.com/",
    "githubUrl": "",
    "linkedinUrl": "",
    "twitterUrl": "",
    "newPasword": "",
    "oldPassword": ""
}

###
// Elimnar Usuario, pasa a estado false, restringido a dueño de la cuenta o rango Administrador.
DELETE  http://localhost:3000/api/users/6062685fa2ce3a0b74948bd5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDYyNjdmY2EyY2UzYTBiNzQ5NDhiZDIiLCJpYXQiOjE2MTczODU4NTUsImV4cCI6MTYxNzQ3MjI1NX0.-tEHZd-DOkRsJDOzodJbAOF4EnbmcodYfK5M1EXsn4A